package com.ambienttv.photosambient.data.model

import java.util.UUID

/**
 * Models the OAuth 2.0 `state` parameter for the Google Photos Ambient API streamlined TV flow.
 *
 * In the streamlined Ambient API authorization flow:
 * - A client-generated UUID v4 `requestId` is passed in the OAuth authorization request.
 * - An optional `displayName` can be included to associate the device display name during sign-in.
 * - This state links the user's mobile authorization with the device registration process.
 *
 * @property requestId Unique UUID v4 generated by the client for this setup session.
 * @property displayName User-assigned name for the ambient device (e.g., "Living Room TV").
 */
data class AmbientOAuthState(
    val requestId: String = UUID.randomUUID().toString(),
    val displayName: String? = null
) {
    /**
     * Serializes this state object into a URL-safe JSON string suitable for the OAuth 2.0 `state` parameter.
     */
    fun toStateParam(): String {
        val escapedName = displayName?.replace("\"", "\\\"")
        return if (escapedName != null) {
            "{\"requestId\":\"$requestId\",\"displayName\":\"$escapedName\"}"
        } else {
            "{\"requestId\":\"$requestId\"}"
        }
    }

    companion object {
        /**
         * Creates a fresh streamlined OAuth state for an ambient device registration session.
         */
        fun create(displayName: String? = "Living Room TV"): AmbientOAuthState {
            return AmbientOAuthState(
                requestId = UUID.randomUUID().toString(),
                displayName = displayName
            )
        }
    }
}